/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...notFond]': RouteRecordInfo<'/[...notFond]', '/:notFond(.*)', { notFond: ParamValue<true> }, { notFond: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mall/order/list/': RouteRecordInfo<'/mall/order/list/', '/mall/order/list', Record<never, never>, Record<never, never>>,
    '/mall/product/category/': RouteRecordInfo<'/mall/product/category/', '/mall/product/category', Record<never, never>, Record<never, never>>,
    '/mall/product/list/': RouteRecordInfo<'/mall/product/list/', '/mall/product/list', Record<never, never>, Record<never, never>>,
    '/mall/product/sku/': RouteRecordInfo<'/mall/product/sku/', '/mall/product/sku', Record<never, never>, Record<never, never>>,
    '/mall/user/miniapp/': RouteRecordInfo<'/mall/user/miniapp/', '/mall/user/miniapp', Record<never, never>, Record<never, never>>,
    '/monitor/logininfor/': RouteRecordInfo<'/monitor/logininfor/', '/monitor/logininfor', Record<never, never>, Record<never, never>>,
    '/monitor/operlog/': RouteRecordInfo<'/monitor/operlog/', '/monitor/operlog', Record<never, never>, Record<never, never>>,
    '/monitor/server/': RouteRecordInfo<'/monitor/server/', '/monitor/server', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/sys_menu/': RouteRecordInfo<'/sys_menu/', '/sys_menu', Record<never, never>, Record<never, never>>,
    '/system/dept/': RouteRecordInfo<'/system/dept/', '/system/dept', Record<never, never>, Record<never, never>>,
    '/system/dict/data/': RouteRecordInfo<'/system/dict/data/', '/system/dict/data', Record<never, never>, Record<never, never>>,
    '/system/dict/type/': RouteRecordInfo<'/system/dict/type/', '/system/dict/type', Record<never, never>, Record<never, never>>,
    '/system/menu/': RouteRecordInfo<'/system/menu/', '/system/menu', Record<never, never>, Record<never, never>>,
    '/system/post/': RouteRecordInfo<'/system/post/', '/system/post', Record<never, never>, Record<never, never>>,
    '/system/role/': RouteRecordInfo<'/system/role/', '/system/role', Record<never, never>, Record<never, never>>,
    '/system/user/': RouteRecordInfo<'/system/user/', '/system/user', Record<never, never>, Record<never, never>>,
    '/table_demo/aside/': RouteRecordInfo<'/table_demo/aside/', '/table_demo/aside', Record<never, never>, Record<never, never>>,
    '/table_demo/base/': RouteRecordInfo<'/table_demo/base/', '/table_demo/base', Record<never, never>, Record<never, never>>,
    '/test/testaa/': RouteRecordInfo<'/test/testaa/', '/test/testaa', Record<never, never>, Record<never, never>>,
  }
}
